### ISSUE TITLE
BUG: 无法发送图片，后台无报错

### ISSUE THREAD

**Issue by rubbish-wang** [A-kirami/whattoeat#14]
### 确认事项

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。

### 影响版本

hoshinobot V2，模拟器shamrock

### 问题描述

[2024-03-30 13:08:08,257 nonebot] INFO: Self: #######, Message 926998025 from
 #######@[群:#######]: '今天吃什么'
[2024-03-30 13:08:08,257 今天吃什么] INFO: Message 926998025 triggered net_ease_
cloud_word.
[2024-03-30 13:08:08,882 nonebot] INFO: Message 926998025 is ignored: Handled by
 Hoshino
![image](https://github.com/A-kirami/whattoeat/assets/54050502/3f03d169-cee5-455b-9c97-a372c2817bf4)

### 复现步骤

1添加模块进hoshinobot
2启用模块
3输入指令
4只生成文字

### 预期行为

图片+文字

### 日志信息

[2024-03-30 13:08:08,257 nonebot] INFO: Self: #######, Message 926998025 from
 #######@[群:#######]: '今天吃什么'
[2024-03-30 13:08:08,257 今天吃什么] INFO: Message 926998025 triggered net_ease_
cloud_word.
[2024-03-30 13:08:08,882 nonebot] INFO: Message 926998025 is ignored: Handled by
 Hoshino

### 参与贡献

- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

**Comment by rubbish-wang** [comment]
[13:58.41]ERROR java.io.FileNotFoundException: C:\Users\Administrator\Desktop\bot\res\img\foods\盖码饭.jpg:open failed:ENOENT (No such file or directory)
at libcore.io.loBridge.open(loBridge.java:575)
at java.io.FilelnputStream.<init>(FilelnputStream.java:160)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Continuationlmpl.kt:33at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.schedulina.CoroutineScheduler.runSafelv(CoroutineScheduler.kt:584)

**Comment by rubbish-wang** [comment]
是我傻了，里面文件编码改hoshinobotbase64
