### ISSUE TITLE
BUG: 在今天吃什么指令被触发时报错

### ISSUE THREAD

**Issue by wdnmda0j** [A-kirami/whattoeat#15]
### 确认事项

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。

### 影响版本

latest

### 问题描述

在HoshinoBot上安装插件后测试时发现在被[今天吃什么]指令触发时发生报错

### 复现步骤

使用的操作系统是Ubuntu 20.04.6 LTS arm64

### 日志信息

Message 524587523 from 3198966175@[群:960983242]: '今天吃什么'
[2024-10-23 18:36:17,045 今天吃什么] INFO: Message 524587523 triggered net_ease_cloud_word.
[2024-10-23 18:36:17,078 今天吃什么] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when net_ease_cloud_word handling message 524587523.
[2024-10-23 18:36:17,079 今天吃什么] ERROR: <ActionFailed status='failed', retcode=1200, data=None, message="Error: ENOENT: no such file or directory, copyfile '//HoshinoBot/res/img/foods/麻辣香锅.jpg' -> '/app/.config/QQ/NapCat/temp/5c9fa46e-2206-4777-bd93-5c78afd7a347.jpg'\n    at Object.copyFileSync (node:fs:3013:11)\n    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)\n    at uri2local (file:///app/napcat/napcat.mjs:5629:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:24008:9)\n    at async Object.image (file:///app/napcat/napcat.mjs:23700:10)\n    at async Promise.all (index 2)\n    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:23953:17)\n    at async SendMsg._handle (file:///app/napcat/napcat.mjs:30719:52)\n    at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:30619:23)", wording="Error: ENOENT: no such file or directory, copyfile '//HoshinoBot/res/img/foods/麻辣香锅.jpg' -> '/app/.config/QQ/NapCat/temp/5c9fa46e-2206-4777-bd93-5c78afd7a347.jpg'\n    at Object.copyFileSync (node:fs:3013:11)\n    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)\n    at uri2local (file:///app/napcat/napcat.mjs:5629:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:24008:9)\n    at async Object.image (file:///app/napcat/napcat.mjs:23700:10)\n    at async Promise.all (index 2)\n    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:23953:17)\n    at async SendMsg._handle (file:///app/napcat/napcat.mjs:30719:52)\n    at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:30619:23)", echo={'seq': 3}>
Traceback (most recent call last):
  File "/HoshinoBot/hoshino/msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "/HoshinoBot/hoshino/modules/whattoeat/whattoeat.py", line 39, in net_ease_cloud_word
    await bot.send(ev, to_eat, at_sender=True)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed status='failed', retcode=1200, data=None, message="Error: ENOENT: no such file or directory, copyfile '//HoshinoBot/res/img/foods/麻辣香锅.jpg' -> '/app/.config/QQ/NapCat/temp/5c9fa46e-2206-4777-bd93-5c78afd7a347.jpg'\n    at Object.copyFileSync (node:fs:3013:11)\n    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)\n    at uri2local (file:///app/napcat/napcat.mjs:5629:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:24008:9)\n    at async Object.image (file:///app/napcat/napcat.mjs:23700:10)\n    at async Promise.all (index 2)\n    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:23953:17)\n    at async SendMsg._handle (file:///app/napcat/napcat.mjs:30719:52)\n    at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:30619:23)", wording="Error: ENOENT: no such file or directory, copyfile '//HoshinoBot/res/img/foods/麻辣香锅.jpg' -> '/app/.config/QQ/NapCat/temp/5c9fa46e-2206-4777-bd93-5c78afd7a347.jpg'\n    at Object.copyFileSync (node:fs:3013:11)\n    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)\n    at uri2local (file:///app/napcat/napcat.mjs:5629:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:24008:9)\n    at async Object.image (file:///app/napcat/napcat.mjs:23700:10)\n    at async Promise.all (index 2)\n    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:23953:17)\n    at async SendMsg._handle (file:///app/napcat/napcat.mjs:30719:52)\n    at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:30619:23)", echo={'seq': 3}>
[2024-10-23 18:36:17,139 nonebot] INFO: Message 524587523 is ignored: Handled by Hoshino

### 参与贡献

- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

**Comment by A-kirami** [comment]
尝试使用 [Matcha](https://github.com/A-kirami/matcha) 检查此问题能否复现
